const products = [
    {
      id: "SnapDeal7",
      name: "New Stylish Fashionable EXPORT Quality denim JEANS FOR MEN",
      img: "/public/products/pant-3.jpg",
      price: 295,
      rating: 4.2,
      stock: 16,
      review: 76,
      category: "jeans",
      topCategory: "Men's",
      feature: true,
      aosDelay: 0,
    },
    {
        _id: "65e15849fbc702b0891afdcf",
        id: "SnapDeal21",
        name: "MI Mini Bag Small Backpack For Men - Bag For Boys",
        img: "/public/products/bag-1.jpg",
        price: 310,
        rating: 5,
        stock: 15,
        review: 51,
        category: "Bags",
        topCategory: "Men's",
        feature: true,
        aosDelay: 200,
        delivery: true,
      },
      {
        _id: "65e15849fbc702b0891afdd1",
        id: "SnapDeal52",
        name: "New Exclusive Collection High Quality Cotton Ari Printed 3 Piece for Women",
        img: "/public/products/three-pice-1.jpg",
        price: 570,
        rating: 4.9,
        stock: 19,
        review: 24,
        category: "Three-Piece",
        topCategory: "Women's",
        feature: true,
        aosDelay: 0,
      },
      {
        _id: "65e15849fbc702b0891afdd2",
        id: "SnapDeal41",
        name: "Olevs Leather Waterproof Quartz Fashion Watch for Men",
        img: "/public/products/watch-1.jpg",
        price: 350,
        rating: 5,
        stock: 9,
        review: 54,
        category: "Watch",
        topCategory: "Men's",
        feature: true,
        aosDelay: 100,
        warranty: true,
      },
      {
        _id: "65e15849fbc702b0891afdd8",
        id: "SnapDeal46",
        name: "Export Quality Cotton Half Pants For Men - 2 Quarter For Men",
        img: "/public/products/short-pant-1.jpg",
        price: 199,
        rating: 4.9,
        stock: 22,
        review: 39,
        category: "Short-Pant",
        topCategory: "Men's",
        feature: true,
        aosDelay: 300,
        delivery: true,
      },
      {
        _id: "65e15849fbc702b0891afdde",
        id: "SnapDeal6",
        name: "Men's Premium Quality Denim Jeans Pants",
        img: "/public/products/pant-2.jpg",
        price: 550,
        rating: 4.6,
        stock: 7,
        review: 34,
        category: "Jeans",
        topCategory: "Men's",
        bestSale: true,
        aosDelay: 100,
      },
      {
        _id: "65e15849fbc702b0891afde0",
        id: "SnapDeal51",
        name: "Summer Panjabi - Embrace the Season with Style in a Fashionable and Comfortable Cotton Long Sleeve Panjabi for Men",
        img: "/public/products/panjabi-4.jpg",
        price: 499,
        rating: 4.9,
        stock: 8,
        review: 98,
        category: "Panjabi",
        topCategory: "Men's",
        bestSale: true,
        aosDelay: 300,
      },
      {
        _id: "65e15849fbc702b0891afde1",
        id: "SnapDeal42",
        name: "TRSOYE New Luxury Fashion Leather Belt Wristwatch for Men, Only Family Touch",
        img: "/public/products/watch-2.jpg",
        price: 310,
        rating: 4.6,
        stock: 17,
        review: 162,
        category: "Watch",
        topCategory: "Men's",
        trending: true,
        aosDelay: 0,
      },
      {
        _id: "65e15849fbc702b0891afde4",
        id: "SnapDeal16",
        name: "Premium Quality Stylish Sneakers Casual Lace-up Shoes Winter and Summer Men's Shoes",
        img: "/public/products/shoe-1.jpg",
        price: 495,
        rating: 5,
        stock: 25,
        review: 37,
        category: "Shoes",
        topCategory: "Men's",
        trending: true,
        aosDelay: 300,
      },
      {
        _id: "65e15849fbc702b0891afde9",
        id: "SnapDeal22",
        name: "15 Inch Stylish Water Resistant Laptop Backpack",
        img: "/public/products/bag-2.jpg",
        price: 650,
        rating: 4.9,
        stock: 9,
        review: 65,
        category: "Bags",
        topCategory: "Men's",
        wholeSale: true,
      },
      {
        _id: "65e15849fbc702b0891afde9",
        id: "SnapDeal22",
        name: "15 Inch Stylish Water Resistant Laptop Backpack",
        img: "/public/products/bag-2.jpg",
        price: 650,
        rating: 4.9,
        stock: 9,
        review: 65,
        category: "Bags",
        topCategory: "Men's",
        wholeSale: true,
      },
      {
        id: "SnapDeal28",
        name: "Fashionable and trendy design sequins hijab",
        img: "/public/products/hijab-2.jpg",
        price: 90,
        rating: 4.8,
        stock: 7,
        review: 23,
        category: "Hijab",
        topCategory: "Women's",
        delivery: true
      },
      {
        _id: "65e15849fbc702b0891afdf4",
        id: "SnapDeal32",
        name: "Blue Color Winter Jacket for Men - Jacket For Men - Jacket For Men",
        img: "/public/products/jacket-3.jpg",
        price: 375,
        rating: 4.5,
        stock: 19,
        review: 76,
        category: "Jacket",
        topCategory: "Men's",
      },
      {
        id: "SnapDeal8",
        name: "New Stylish Fashionable EXPORT Quality denim JEANS FOR MEN",
        img: "/public/products/pant-4.jpg",
        price: 295,
        rating: 4.8,
        stock: 9,
        review: 54,
        category: "jeans",
        topCategory: "Men's"
      },
      {
        id: "SnapDeal25",
        name: "IELGY Black high-quality texture strap design shoulder bag hundred women",
        img: "/public/products/bag-5.jpg",
        price: 1930,
        rating: 4.6,
        stock: 10,
        review: 28,
        category: "Bags",
        topCategory: "Women's",
        delivery: true
      },
      {
        id: "SnapDeal20",
        name: "Fabric Sneaker for Women - Golapi",
        img: "/public/products/shoe-5.jpg",
        price: 300,
        rating: 4.2,
        stock: 8,
        review: 73,
        category: "Shoes",
        topCategory: "Women's"
      },
      {
        id: "SnapDeal48",
        name: "White Panjabi with Chest Contrast. Soft Cotton, Panjabi for men Brand new design. Stylish and trendy Item",
        img: "/public/products/panjabi-1.jpg",
        price: 390,
        rating: 4.9,
        stock: 16,
        review: 29,
        category: "Panjabi",
        topCategory: "Men's",
        feature: true,
        aosDelay: 200
      },
      {
        id: "SnapDeal30",
        name: "Stylish Printed Jacket with pant For Man - Jacket For Men",
        img: "/public/products/jacket-1.jpg",
        price: 599,
        rating: 4.3,
        stock: 11,
        review: 98,
        category: "Jacket",
        topCategory: "Men's",
        feature: true,
        aosDelay: 300
      },
      {
        id: "SnapDeal18",
        name: "Stylish Multicolore Colore Winter Sneakers for Men",
        img: "/public/products/shoe-3.jpg",
        price: 399,
        rating: 4.5,
        stock: 9,
        review: 47,
        category: "Shoes",
        topCategory: "Men's",
        feature: true,
        aosDelay: 100,
        wholeSale: true
      },
      {
        id: "SnapDeal35",
        name: "Water Proof Music Flower Gel Black And Brown 2-Color Gel Eyeliner",
        img: "/public/products/makeup-2.jpg",
        price: 155,
        rating: 4.1,
        stock: 11,
        review: 45,
        category: "Makeup",
        topCategory: "Women's",
        feature: true,
        aosDelay: 200,
        delivery: true
      },
      {
        id: "SnapDeal39",
        name: "Baby Katan Shari - Child Katan - Baccader Katan Saree Sisuder Tat Shari - Special Occasion Share - Tangail Katan Share - Gift Saree - Paka Rong - Festival Sarees - Holud er Sharees - 9 Hat Sari",
        img: "/public/products/Shari-2.jpg",
        price: 310,
        rating: 4.6,
        stock: 13,
        review: 23,
        category: "Shari",
        topCategory: "Women's",
        feature: true,
        aosDelay: 0
      },
      {
        id: "SnapDeal26",
        name: "Artificial Leather Fashonable hand Bag for Women",
        img: "/public/products/bag-6.jpg",
        price: 250,
        rating: 3.8,
        stock: 17,
        review: 23,
        category: "Bags",
        topCategory: "Women's",
        feature: true,
        aosDelay: 100
      },
      {
        id: "SnapDeal13",
        name: "Silk Boy Newborn Baby Winter Dress, Age Group: 0-3 Months",
        img: "/public/products/kids-4.jpg",
        price: 1200,
        rating: 4.4,
        stock: 21,
        review: 27,
        category: "Kids",
        topCategory: "Kids",
        bestSale: true,
        aosDelay: 0
      },
      {
        id: "SnapDeal3",
        name: "Oxford Fabrics Green Color Long Sleeve Shirt For Men - Shirt For Men - Shirt",
        img: "/public/products/shirt-3.jpg",
        price: 395,
        rating: 4.8,
        stock: 19,
        review: 87,
        category: "T-Shirt",
        bestSale: true,
        aosDelay: 200
      },
      {
        id: "SnapDeal40",
        name: "Semi Katan Saree for Women - A Stunning Saree Option Without Blouse Pieces - Ideal for Special Occasions",
        img: "/public/products/Shari-3.jpg",
        price: 750,
        rating: 4.2,
        stock: 8,
        review: 76,
        category: "Shari",
        topCategory: "Women's",
        trending: true,
        aosDelay: 200
      },
      {
        id: "SnapDeal38",
        name: "Tangail Tat silk Shari",
        img: "/public/products/Shari-1.jpg",
        price: 320,
        rating: 5,
        stock: 7,
        review: 76,
        category: "Shari",
        topCategory: "Women's"
      },
      {
        id: "SnapDeal53",
        name: "Trendsetter -Indian New Stylish Exclushive Collection Weatless Goergett Computer Abroydary Work 4 Piece Salower Kameez For Women- Inventive Choice",
        img: "/public/products/three-pice-2.jpg",
        price: 550,
        rating: 4.4,
        stock: 12,
        review: 76,
        category: "Three-Pice",
        topCategory: "Women's"
      },
      {
        id: "SnapDeal50",
        name: "Holuder fasionable panjabi various occasionally panjabi",
        img: "/public/products/panjabi-3.jpg",
        price: 230,
        rating: 4.2,
        stock: 7,
        review: 24,
        category: "Panjabi",
        topCategory: "Men's",
        wholeSale: true
      },
      {
        id: "SnapDeal43",
        name: "OLEVS Leather Quartz Fashion Watch for Men!",
        img: "/public/products/watch-3.jpg",
        price: 320,
        rating: 4,
        stock: 12,
        review: 18,
        category: "Watch",
        topCategory: "Men's",
        warranty: true
      },
      {
        id: "SnapDeal2",
        name: "New Stylish & Fashionable Full Sleeve Formal Shirts For Men",
        img: "/public/products/shirt-2.jpg",
        price: 249,
        rating: 4.7,
        stock: 13,
        review: 87,
        category: "T-Shirt",
        topCategory: "Men's",
        wholeSale: true
      },
      {
        id: "SnapDeal11",
        name: "Boys Summer Dress for Baby",
        img: "/public/products/kids-2.jpg",
        price: 1499,
        rating: 4.2,
        stock: 18,
        review: 92,
        category: "Kids",
        topCategory: "Kids"
      },
      {
        id: "SnapDeal37",
        name: "Belenda beauty lip tint",
        img: "/public/products/makeup-4.jpg",
        price: 90,
        rating: 4.6,
        stock: 16,
        review: 76,
        category: "Makeup",
        topCategory: "Women's",
        warranty: true,
        delivery: true
      },
      {
        id: "SnapDeal44",
        name: "POEDAGAR 368 Women Fashion Luxury Watch",
        img: "/public/products/watch-4.jpg",
        price: 1450,
        rating: 5,
        stock: 16,
        review: 38,
        category: "Watch",
        topCategory: "Men's",
        warranty: true,
        wholeSale: true
      },
      {
        id: "SnapDeal10",
        name: "Party Clothing Dress Set for Baby Boys",
        img: "/public/products/kids-1.jpg",
        price: 1699,
        rating: 4.9,
        stock: 14,
        review: 122,
        category: "Kids",
        topCategory: "Kids",
        feature: true,
        aosDelay: 300
      },
      {
        id: "SnapDeal1",
        name: "New Long Sleeve Casual Shirt for Men",
        img: "/public/products/shirt-1.jpg",
        price: 396,
        rating: 5,
        stock: 17,
        review: 73,
        category: "T-Shirt",
        topCategory: "Men's",
        feature: true,
        aosDelay: 100
      },
      {
        id: "SnapDeal49",
        name: "Men'S Panjabi Premium Semi Long Embroidery Work Panjabi For Men ( Snap Button)",
        img: "/public/products/panjabi-2.jpg",
        price: 850,
        rating: 4.6,
        stock: 9,
        review: 76,
        category: "Panjabi",
        topCategory: "Men's",
        feature: true,
        aosDelay: 200
      },
      {
        id: "SnapDeal27",
        name: "Chiffon Georgette Hijab Women Soft Fabric (Jorjet) Hijab - Elevate Style Soft Chiffon Georgette Hijab, Perfect For Modest And Elegant Outfits",
        img: "/public/products/hijab-1.jpg",
        price: 165,
        rating: 5,
        stock: 19,
        review: 83,
        category: "Hijab",
        topCategory: "Women's",
        feature: true,
        aosDelay: 300,
        delivery: true,
      },
      {
        id: "SnapDeal31",
        name: "Stylish Premium Winter Jacket For Men",
        img: "/public/products/jacket-2.jpg",
        price: 655,
        rating: 4.9,
        stock: 17,
        review: 45,
        category: "Jacket",
        topCategory: "Men's",
        trending: true,
        aosDelay: 100,
      },
      {
        id: "SnapDeal57",
        name: "Jaspeer Wholesale Retro Band Polarized Sunglasses for Men",
        img: "/public/products/sunglass-3.jpg",
        price: 250,
        rating: 4.3,
        stock: 22,
        review: 65,
        category: "Sunglass",
        topCategory: "Men's",
        delivery: true,
      },
      {
        id: "SnapDeal17",
        name: "Luxury Fashionable casual shoes Sneakers For Men (White)",
        img: "/public/products/shoe-2.jpg",
        price: 340,
        rating: 4.1,
        stock: 6,
        review: 52,
        category: "Shoes",
        topCategory: "Men's",
      },
      {
        id: "SnapDeal4",
        name: "Teal Colour Long Sleeve Casual Shirt For Man",
        img: "/public/products/shirt-4.jpg",
        price: 410,
        rating: 4.1,
        stock: 13,
        review: 37,
        category: "T-Shirt",
        topCategory: "Men's",
      },
      {
        id: "SnapDeal12",
        name: "Unisex Baby Clothes Winter Coats Cute",
        img: "/public/products/kids-3.jpg",
        price: 950,
        rating: 4.8,
        stock: 11,
        review: 85,
        category: "Kids",
        topCategory: "Kids",
      },
      {
        id: "SnapDeal34",
        name: "Bamboo Makeup Brush Set - 11 PCS",
        img: "/public/products/makeup-1.jpg",
        price: 308,
        rating: 5,
        stock: 9,
        review: 87,
        category: "Makeup",
        topCategory: "Women's",
        delivery: true,
      },
      {
        _id: "65e15849fbc702b0891afdfd",
        id: "SnapDeal55",
        name: "Achieve a Trendy Look with Too Stylish Black Sunglasses for Men - Very Comfortable and Fashionable, Easy to Clean - Embrace Sunglasses Fashion.",
        img: "/public/products/sunglass-1.jpg",
        price: 180,
        rating: 4.9,
        stock: 22,
        review: 65,
        category: "Sunglass",
        topCategory: "Men's",
        delivery: true,
      },
      {
        _id: "65e15849fbc702b0891afe03",
        id: "SnapDeal45",
        name: "Carat 2Pcs/3Pcs/Set Women Watch Bracelet Kit Round Dial Shiny Rhinestones Inlaid Roman Numerals Decorative Gift Lady Quartz Wristwatch",
        img: "/public/products/watch-5.jpg",
        price: 519,
        rating: 4.3,
        stock: 9,
        review: 93,
        category: "Watch",
        topCategory: "Men's",
        warranty: true,
      },
      {
        _id: "65e15849fbc702b0891afdd5",
        id: "SnapDeal56",
        name: "Retro Female Polygonal Crystal Sunglasses -Anti-UV Sports Sunshade Eyeglasses Creative Trimmed Round Face Thin Sun Glasses",
        img: "/public/products/sunglass-2.jpg",
        price: 260,
        rating: 4.4,
        stock: 22,
        review: 65,
        category: "Sunglass",
        topCategory: "Men's",
        feature: true,
        aosDelay: 0,
        delivery: true,
      },
      {
        id: "SnapDeal23",
        name: "Outdoor Travel Bag For Boy & Girl Waterproof Bag Men & Women Backpack 10L",
        img: "/public/products/bag-3.jpg",
        price: 200,
        rating: 4.5,
        stock: 17,
        review: 28,
        category: "Bags",
        topCategory: "Men's",
        delivery: true
      },
      {
        id: "SnapDeal5",
        name: "New Stylish Fashionable EXPORT Quality denim JEANS FOR MEN",
        img: "/public/products/pant-1.jpg",
        price: 350,
        rating: 5,
        stock: 10,
        review: 76,
        category: "jeans",
        topCategory: "Men's"
      },
      {
        id: "SnapDeal36",
        name: "18 Colors eyeshadow pallete Glitter Makeup Matte Eye shadow make up palette",
        img: "/public/products/makeup-3.jpg",
        price: 233,
        rating: 4.9,
        stock: 21,
        review: 87,
        category: "Makeup",
        topCategory: "Women's",
        delivery: true
      },
      {
        id: "SnapDeal9",
        name: "Indigo Co Premium Jeans Pant- Slim Fit (Ind 002) - Pant",
        img: "/public/products/pant-5.jpg",
        price: 430,
        rating: 4.5,
        stock: 27,
        review: 94,
        category: "jeans",
        topCategory: "Men's",
        wholeSale: true
      },
      {
        id: "SnapDeal19",
        name: "Light Pink Sneaker -Net Fabric",
        img: "/public/products/shoe-4.jpg",
        price: 890,
        rating: 4.8,
        stock: 11,
        review: 38,
        category: "Shoes",
        topCategory: "Women's"
      },
      {
        id: "SnapDeal47",
        name: "Black Mans Comfortable Cotton Cargo Shorts Half Pants - Short Pant For Men",
        img: "/public/products/short-pant-2.jpg",
        price: 190,
        rating: 4.3,
        stock: 12,
        review: 83,
        category: "Short-Pant",
        topCategory: "Men's",
        delivery: true
      },
      {
        id: "SnapDeal54",
        name: "Exclusive Fashionable Stylish and Comfortable Salwar Kameez for Women",
        img: "/public/products/three-pice-3.jpg",
        price: 469,
        rating: 4.9,
        stock: 22,
        review: 65,
        category: "Three-Pice",
        topCategory: "Women's",
        wholeSale: true
      },
      {
        id: "SnapDeal33",
        name: "Men's Winter Jacket ((-GRAY-BLACK-))",
        img: "/public/products/jacket-4.jpg",
        price: 545,
        rating: 5,
        stock: 13,
        review: 57,
        category: "Jacket",
        topCategory: "Men's"
      },
      {
        id: "SnapDeal15",
        name: "Dress For Baby Boy Half-Sleeve T-shirt Set with Koti and Pant (06Months-7) Years",
        img: "/public/products/kids-5.jpg",
        price: 1550,
        rating: 4.9,
        stock: 16,
        review: 26,
        category: "Kids",
        topCategory: "Kids"
      }
  ];
  
  export default products;
  
